### ISSUE TITLE
Examples are out of date?

### ISSUE THREAD

**Issue by hairychris** [zzzsochi/aiotraversal#1]
This is a great library but due to recent changes the examples have become out of date. I thought it might be good to start this issue to keep track of what changes need to be made to bring them back in line. I don't mind helping out where possible.
1. The new way of starting an application has not been added to the examples (does the old way still work?)

**Comment by zzzsochi** [comment]
Oh... I will fix it of these days.

**Comment by zzzsochi** [comment]
Fixed.
