### ISSUE TITLE
How to reverse url?

### ISSUE THREAD

**Issue by binhnq94** [zzzsochi/aiotraversal#2]
Do aiotraversal provide reverse url function like django reverse?

**Comment by zzzsochi** [comment]
Do you mean "reverse"?
https://github.com/zzzsochi/aiohttp_traversal/blob/master/aiohttp_traversal/traversal.py#L76
`'/'.join(reversed(r.__name__ for r in lineage(self)))`?

**Comment by binhnq94** [comment]
yes!
i mean "Do aiotraversal provide reverse url function like https://docs.djangoproject.com/en/1.9/ref/urlresolvers/"?
If yes, how to use it?

**Comment by zzzsochi** [comment]
Use `lineage` function for create url for specified resource.

**Comment by binhnq94** [comment]
ok. thanks u.
